variables:
#  EXTRA_DNF_REPOS: |
#    [KiranBase2.4]
#    name=KiranBase2.4
#    gpgcheck=0
#    baseurl=http://192.168.120.71/kojifiles/repos/KY3.5-1-Kiran-base-2.4-build/latest/x86_64/
  RPM_BUILD_REQUIRES: 'gcc-c++ cmake glib2-devel qt5-qtbase-devel qt5-linguist kiran-log-qt5-devel kiran-widgets-qt5-devel kiran-qt5-integration-devel'
  IMAGE: 'kylinsec-3.4-5-gc'

include:
  - project: 'os/gitlab-ci'
    ref: main
    file: '/cmake/cxx.gitlab-ci.yml'
