variables:
  RPM_BUILD_REQUIRES: 'gcc-c++ cmake glib2-devel qt5-qtbase-devel qt5-linguist kiran-log-qt5-devel kiran-widgets-qt5-devel'

include:
  - project: 'os/gitlab-ci'
    ref: main
    file: '/cmake/cxx.gitlab-ci.yml'
